[development]
accounts = ["default"]

# [development.network]
# rpc-url = "http://localhost:8000/rpc"
# network-passphrase = "Standalone Network ; February 2017"
# run-locally = true

# Testnet
[development.network]
rpc-url = "https://soroban-testnet.stellar.org"
network-passphrase = "Test SDF Network ; September 2015"
run-locally = false

[development.contracts]

[development.contracts.ultrahonk_soroban_contract]
client = true

[development.contracts.guess_the_puzzle]
client = true
constructor_args = """
--admin default
"""

[development.contracts.slice]
client = true
constructor_args = """
--admin default
--min_pay_seconds 300
--max_pay_seconds 86400
--min_commit_seconds 300
--max_commit_seconds 86400
--min_reveal_seconds 300
--max_reveal_seconds 86400
"""
